const express = require("express");
const router = express.Router();
const Application = require("../models/Application");
const authenticateToken = require("../middleware/auth");
const nodemailer = require("nodemailer");

// Function to dispatch SMTP email notification for candidate applications
const sendApplicationEmail = async (application) => {
  try {
    const smtpHost = process.env.SMTP_HOST || "smtp.gmail.com";
    const smtpPort = parseInt(process.env.SMTP_PORT || "587");
    const smtpUser = process.env.SMTP_USER;
    const smtpPass = process.env.SMTP_PASS;
    const emailTo = process.env.EMAIL_TO || "info@labelzai.in";

    if (!smtpUser || !smtpPass) {
      console.warn("Nodemailer SMTP credentials (SMTP_USER, SMTP_PASS) not set in .env. Skipping application email dispatch.");
      return;
    }

    const transporterConfig = {
      auth: {
        user: smtpUser,
        pass: smtpPass,
      },
    };

    if (smtpHost.toLowerCase() === "smtp.gmail.com") {
      transporterConfig.service = "gmail";
    } else {
      transporterConfig.host = smtpHost;
      transporterConfig.port = smtpPort;
      transporterConfig.secure = smtpPort === 465;
    }

    const transporter = nodemailer.createTransport(transporterConfig);

    // Extract raw base64 string (remove data URL prefix if present)
    const base64Content = application.resumeData.includes("base64,")
      ? application.resumeData.split("base64,")[1]
      : application.resumeData;

    const mailOptions = {
      from: `"LabelzAI Careers Portal" <${smtpUser}>`,
      to: emailTo,
      subject: `New Job Application: ${application.fullName} - ${application.jobTitle}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; border: 1px solid #e2e8f0; border-radius: 12px; padding: 24px; color: #0b2545;">
          <h2 style="border-bottom: 2px solid #0b2545; padding-bottom: 10px; color: #0b2545; font-weight: normal; margin-top: 0;">New Job Application Received</h2>
          <p style="font-size: 14px; color: #64748b; margin-bottom: 20px;">A candidate has applied for a vacant position through the careers portal.</p>
          
          <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
            <tr style="background: #f8fafc;">
              <td style="padding: 8px 12px; font-weight: bold; width: 140px;">Position Applied:</td>
              <td style="padding: 8px 12px;"><strong>${application.jobTitle}</strong></td>
            </tr>
            <tr>
              <td style="padding: 8px 12px; font-weight: bold;">Candidate Name:</td>
              <td style="padding: 8px 12px;">${application.fullName}</td>
            </tr>
            <tr style="background: #f8fafc;">
              <td style="padding: 8px 12px; font-weight: bold;">Email Address:</td>
              <td style="padding: 8px 12px;"><a href="mailto:${application.email}" style="color: #0b2545; text-decoration: underline;">${application.email}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 12px; font-weight: bold;">Phone Number:</td>
              <td style="padding: 8px 12px;"><a href="tel:${application.phone}" style="color: #0b2545; text-decoration: underline;">${application.phone}</a></td>
            </tr>
            <tr style="background: #f8fafc;">
              <td style="padding: 8px 12px; font-weight: bold;">Experience:</td>
              <td style="padding: 8px 12px;">${application.experience}</td>
            </tr>
          </table>
          
          ${application.coverLetter ? `
          <div style="margin-top: 24px;">
            <h4 style="margin-bottom: 8px; color: #0b2545;">Cover Letter / Message:</h4>
            <div style="background: #f8fafc; border-left: 4px solid #0b2545; padding: 12px 16px; border-radius: 4px; font-size: 14px; line-height: 1.6; color: #334155;">
              ${application.coverLetter.replace(/\n/g, "<br>")}
            </div>
          </div>` : ""}

          <div style="margin-top: 24px; padding: 12px; background: #f0fdf4; border: 1px dashed #bbf7d0; border-radius: 8px; text-align: center; font-size: 13px; color: #166534;">
            📎 Candidate resume (<strong>${application.resumeName}</strong>) has been attached to this email.
          </div>
          
          <p style="font-size: 11px; color: #94a3b8; margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 12px; text-align: center;">
            This email was auto-generated by the LabelzAI Portal server.
          </p>
        </div>
      `,
      attachments: [
        {
          filename: application.resumeName,
          content: Buffer.from(base64Content, "base64"),
        }
      ]
    };

    const info = await transporter.sendMail(mailOptions);
    console.log("SUCCESS: Application email notification dispatched. Msg ID:", info.messageId);
  } catch (error) {
    console.error("ERROR: Failed to dispatch application email notification:", error.message);
  }
};

// GET /api/applications: Fetch all candidate applications (Protected)
router.get("/", authenticateToken, async (req, res) => {
  try {
    const applications = await Application.find().sort({ createdAt: -1 });
    return res.json({ success: true, data: applications });
  } catch (error) {
    console.error("GET applications error:", error);
    return res.status(500).json({ success: false, error: "Internal Server Error" });
  }
});

// POST /api/applications: Candidate submits application (Public)
router.post("/", async (req, res) => {
  try {
    const {
      jobId,
      jobTitle,
      fullName,
      email,
      phone,
      experience,
      coverLetter,
      resumeName,
      resumeData,
    } = req.body;

    // Validation
    if (
      !jobId ||
      !jobTitle ||
      !fullName ||
      !email ||
      !phone ||
      !experience ||
      !resumeName ||
      !resumeData
    ) {
      return res.status(400).json({
        success: false,
        error: "Missing required application parameters",
      });
    }

    const newApplication = new Application({
      jobId,
      jobTitle,
      fullName,
      email,
      phone,
      experience,
      coverLetter: coverLetter || "",
      resumeName,
      resumeData,
    });

    await newApplication.save();

    // Trigger email notification asynchronously
    sendApplicationEmail(newApplication);

    return res.json({ success: true, data: newApplication });
  } catch (error) {
    console.error("POST application error:", error);
    return res.status(500).json({ success: false, error: "Internal Server Error" });
  }
});

// DELETE /api/applications: Remove a candidate application (Protected)
router.delete("/", authenticateToken, async (req, res) => {
  try {
    const id = req.query.id || req.body.id;

    if (!id) {
      return res.status(400).json({ success: false, error: "Application ID is required" });
    }

    const deletedApp = await Application.findByIdAndDelete(id);
    if (!deletedApp) {
      return res.status(404).json({ success: false, error: "Application record not found" });
    }

    return res.json({ success: true, message: "Application deleted successfully" });
  } catch (error) {
    console.error("DELETE application error:", error);
    return res.status(500).json({ success: false, error: "Internal Server Error" });
  }
});

module.exports = router;
