const express = require("express");
const router = express.Router();
const Enquiry = require("../models/Enquiry");
const authenticateToken = require("../middleware/auth");
const nodemailer = require("nodemailer");

// Function to dispatch SMTP email notification
const sendEnquiryEmail = async (enquiry) => {
  try {
    const smtpHost = process.env.SMTP_HOST || "smtp.gmail.com";
    const smtpPort = parseInt(process.env.SMTP_PORT || "587");
    const smtpUser = process.env.SMTP_USER;
    const smtpPass = process.env.SMTP_PASS;
    const emailTo = process.env.EMAIL_TO || "info@labelzai.in";

    if (!smtpUser || !smtpPass) {
      console.warn("Nodemailer SMTP credentials (SMTP_USER, SMTP_PASS) not set in .env. Skipping email dispatch.");
      return;
    }

    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: smtpPort,
      secure: smtpPort === 465,
      auth: {
        user: smtpUser,
        pass: smtpPass,
      },
    });

    const mailOptions = {
      from: `"LabelzAI Sourcing Lead" <${smtpUser}>`,
      to: emailTo,
      subject: `New Corporate Sourcing Enquiry from ${enquiry.fullName}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; border: 1px solid #e2e8f0; border-radius: 12px; padding: 24px; color: #0b2545;">
          <h2 style="border-bottom: 2px solid #0b2545; padding-bottom: 10px; color: #0b2545; font-weight: normal; margin-top: 0;">New Sourcing Mandate / Enquiry</h2>
          <p style="font-size: 14px; color: #64748b; margin-bottom: 20px;">You have received a new business lead from the LabelzAI website contact form.</p>
          
          <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
            <tr style="background: #f8fafc;">
              <td style="padding: 8px 12px; font-weight: bold; width: 140px;">Contact Name:</td>
              <td style="padding: 8px 12px;">${enquiry.fullName}</td>
            </tr>
            <tr>
              <td style="padding: 8px 12px; font-weight: bold;">Email Address:</td>
              <td style="padding: 8px 12px;"><a href="mailto:${enquiry.email}" style="color: #0b2545; text-decoration: underline;">${enquiry.email}</a></td>
            </tr>
            <tr style="background: #f8fafc;">
              <td style="padding: 8px 12px; font-weight: bold;">Phone Number:</td>
              <td style="padding: 8px 12px;"><a href="tel:${enquiry.phone}" style="color: #0b2545; text-decoration: underline;">${enquiry.phone}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 12px; font-weight: bold;">Organization:</td>
              <td style="padding: 8px 12px;">${enquiry.companyName || "Not Provided"}</td>
            </tr>
          </table>
          
          <div style="margin-top: 24px;">
            <h4 style="margin-bottom: 8px; color: #0b2545;">Sourcing Mandates / Message:</h4>
            <div style="background: #f8fafc; border-left: 4px solid #0b2545; padding: 12px 16px; border-radius: 4px; font-style: italic; font-size: 14px; line-height: 1.6; color: #334155;">
              ${enquiry.message.replace(/\n/g, "<br>")}
            </div>
          </div>
          
          <p style="font-size: 11px; color: #94a3b8; margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 12px; text-align: center;">
            This email was auto-generated by the LabelzAI Portal server.
          </p>
        </div>
      `,
    };

    const info = await transporter.sendMail(mailOptions);
    console.log("SUCCESS: Enquiry email notification dispatched. Msg ID:", info.messageId);
  } catch (error) {
    console.error("ERROR: Failed to dispatch enquiry email notification:", error.message);
  }
};

// GET /api/enquiries: Fetch all enquiries (Protected)
router.get("/", authenticateToken, async (req, res) => {
  try {
    const enquiries = await Enquiry.find().sort({ createdAt: -1 });
    return res.json({ success: true, data: enquiries });
  } catch (error) {
    console.error("GET enquiries error:", error);
    return res.status(500).json({ success: false, error: "Internal Server Error" });
  }
});

// POST /api/enquiries: Submit details (Public)
router.post("/", async (req, res) => {
  try {
    const { fullName, email, phone, companyName, message } = req.body;

    if (!fullName || !email || !phone || !message) {
      return res.status(400).json({ success: false, error: "Missing required enquiry parameters" });
    }

    const newEnquiry = new Enquiry({
      fullName,
      email,
      phone,
      companyName: companyName || "",
      message,
    });

    await newEnquiry.save();

    // Trigger email notification asynchronously
    sendEnquiryEmail(newEnquiry);

    return res.json({ success: true, data: newEnquiry });
  } catch (error) {
    console.error("POST enquiry error:", error);
    return res.status(500).json({ success: false, error: "Internal Server Error" });
  }
});

// DELETE /api/enquiries: Remove an enquiry record (Protected)
router.delete("/", authenticateToken, async (req, res) => {
  try {
    const id = req.query.id || req.body.id;
    if (!id) {
      return res.status(400).json({ success: false, error: "Enquiry ID is required" });
    }

    const deletedEnquiry = await Enquiry.findByIdAndDelete(id);
    if (!deletedEnquiry) {
      return res.status(404).json({ success: false, error: "Enquiry record not found" });
    }

    return res.json({ success: true, message: "Enquiry record deleted successfully" });
  } catch (error) {
    console.error("DELETE enquiry error:", error);
    return res.status(500).json({ success: false, error: "Internal Server Error" });
  }
});

module.exports = router;
